#
#server:
#  port: 8888
#
#spring:
#  application:
#    name: configuration-services
#  profiles:
#    active:
#      - git
#  cloud:
#    config:
#      server:
#        git:
##          uri: https://github.com/PacktPublishing/Software-Architecture-with-Spring-6.0/tree/main/ch7/configurations
#          uri: https://github.com/wandersonxs/online-auction-configuration.git
#          default-label: main
##          search-paths: authentication-services
##
##eureka:
##  instance:
##
##    preferIpAddress: true
##  client:
##    register-with-eureka: true
##    fetch-registry: true
##    serviceUrl:
##      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}